# Generated by Django 3.1.1 on 2020-09-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_users_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='total_views',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
