# Generated by Django 3.1.1 on 2020-09-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_total_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='total_views',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
