# Generated by Django 3.1.1 on 2020-10-02 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20201001_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='users_like',
            new_name='likes',
        ),
    ]
