# Generated by Django 3.1.1 on 2020-10-06 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='likes',
            new_name='user_like',
        ),
    ]
