# Generated by Django 3.1.1 on 2020-09-27 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_email_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_confirmed',
        ),
    ]
